name: Build and deploy Next.js app to Azure Web App - nextjsdummy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r .next deploy/
          cp -r public deploy/
          cp package.json package-lock.json deploy/
          cp -r node_modules deploy/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B787F96329D24343841AA29F247810B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_953424A46BB147198E9AF5AE37B751F6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_65DF1559BE634502BE55C9AA799BD60F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nextjsdummy'
          slot-name: 'Production'
          package: .
